//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRHHOrtiz.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapacitacionesCandidato
    {
        public int CapacitacionesCandidatosId { get; set; }
        public int CapacitacionId { get; set; }
        public int CandidatoId { get; set; }
    
        public virtual Candidato Candidato { get; set; }
        public virtual Capacitacione Capacitacione { get; set; }
    }
}
