//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRHHOrtiz.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int EmpleadoId { get; set; }
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string Departamento { get; set; }
        public string Puesto { get; set; }
        public decimal Salario { get; set; }
        public bool Estado { get; set; }
        public Nullable<int> CandidatoId { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
    
        public virtual Candidato Candidato { get; set; }
    }
}
