//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRHHOrtiz.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperienciasLaborale
    {
        public int ExperienciaLaboralId { get; set; }
        public int CandidatoId { get; set; }
        public string Empresa { get; set; }
        public string PuestoOcupado { get; set; }
        public System.DateTime FechaDesde { get; set; }
        public System.DateTime FechaHasta { get; set; }
        public decimal Salario { get; set; }
    
        public virtual Candidato Candidato { get; set; }
    }
}
